name: Print Hello
on:
  pull_request:
jobs:
  print_hello:
    name: "Print Hello"
    runs-on: linux.2xlarge
    env:
      REF_TYPE: ${{ github.ref_type }}
      LIMIT: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha}}
    steps:
      - name: Print Hello
        run: |
          echo "Hello World"
